### ISSUE TITLE
Order of header/nav

### ISSUE THREAD

**Issue by JordynD** [JordynD/code-a-website#2]
<img width="425" alt="Screen Shot 2021-03-02 at 12 20 32 AM" src="https://user-images.githubusercontent.com/77690445/109601719-5d888d00-7aed-11eb-9402-5c1109555a5b.png">
Not sure how to fix these 2 errors. They are my only remaining errors and I can't seem to figure them out. Thank you! @hellachella

**Comment by JordynD** [comment]
@carolsinc

**Comment by carolsinc** [comment]
On your berries index page your h1 needs to be inside your main tag. The line "There are lots of berries in many different sizes & shapes..." needs a p tag. You should never have content without a tag. You also need roles on your header and nav.

**Comment by carolsinc** [comment]
For your navigation, when you are in the berries folder and linking to the berries index you do not need to include ../berries/ for the berries index page.

**Comment by JordynD** [comment]
Thank you so much Carol!!! If you could help me with my very final error message I would be very grateful! @carolsinc
<img width="477" alt="Screen Shot 2021-03-12 at 11 10 30 AM" src="https://user-images.githubusercontent.com/77690445/110966743-97deff00-8323-11eb-8168-7dfdcfcd2348.png">
